### ISSUE TITLE
Websocket URI doesn't point to correct server

### ISSUE THREAD

**Issue by noobymatze** [hpatjens/Programmierwettbewerb#1]
The Websocket URI over at http://cagine.fh-wedel.de:8080/game.html points to ws://213.39.232.220:8080/gui, just showing a black screen.

Locally pointing the URI to ws://cagine.fh-wedel.de:8080/gui fixes this.

**Comment by MauriceGit** [comment]
Yes, it does. The Ip represents exactly the hostname, so normally should work just fine (for me even on mobile).

The ip-address is also generated on the fly when starting the server and adapts to whatever IP address the server starts on (Gets its own public IP. Thats also why it should work out of the box!). 
It would probably be challenging to change it to a possible host address...

>> curl ipinfo.io/213.39.232.220
{
  "ip": "213.39.232.220",
  "hostname": "cagine.fh-wedel.de",
  "city": "",
  "region": "",
  "country": "DE",
  "loc": "51.0000,9.0000",
  "org": "AS13184 Telefonica Germany GmbH & Co.OHG"
}
