### ISSUE TITLE
Disconnected clients living forever

### ISSUE THREAD

**Issue by NobbZ** [hpatjens/Programmierwettbewerb#2]
Hi there!

I played around with my bot and wanted to restart it after a very slight change of code. After `^C`-ing the middleware, the corresponding blob moved to the last sent target position and is now waiting there for getting swallowed (will probably not happen that quickly, it has a mass of about 10k).

There is also another (living) bot of mine on the server, and I do fear to kill it locally, just to have another dead blob waiting for getting swallowed as it is about 10k as well.

And while I wrote this, the first one got hit by poison and has been split and partially eaten, but it is still about 5k mass.

Can't we timeout disconnected clients and remove them from the grid?

**Comment by NobbZ** [comment]
OK, in the meantime the first bot got split again and has been swallowed completely.

**Comment by MauriceGit** [comment]
Yes, as of right now, we do not delete bots just because the connection is terminated.

But people seem to be irritated by that. So we will update accordingly and just keep living bots on the field!

I will close the issue, when its done!

**Comment by NobbZ** [comment]
Maybe give an option to take over an old connection/hotswap the bot? That would be even cooler!
