### ISSUE TITLE
Middleware keeps disconnecting

### ISSUE THREAD

**Issue by KlixxOne** [hpatjens/Programmierwettbewerb#4]
When starting multiple bots at once using the -numBots flag, my bot does not receive any input after some time (15min or so). The bot then disappears from gui as your server doesnt get any feedback anymore. So I killed the process using CTRL+C:
`^CTraceback (most recent call last):
  File "./run.py", line 730, in <module>
    parseInput()`
`File "./run.py", line 656, in parseInput
    INPUT_STRING = sys.stdin.readline()
KeyboardInterrupt`

I'm using python 2.7 and the most recent version of your middleware.

Is this behavior intended? If not, how can I avoid this disconnecting thingy?

Thanks a lot in Advance!
Felix, pwb_22

**Comment by MauriceGit** [comment]
Hi Felix,

after 15 minutes of actively playing? 
When your bot gets eaten, the bot is deleted on the server and will not get any input/feedback any more. But if you start multiple bots, the middleware will keep running.
If that is your case, this is intended behaviour. Killing the middleware process (CTRL+C) will kill all started bots.

The server itself doesn't care, if a middleware sends commands or not. Not even once. So if your bot never prints anything to stdout, your bot will still live on the server until it gets eaten.

If you have any more questions, feel free to ask :)
And if it is of general concern, maybe consider the Newsgroup.

Maurice
